#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y  += inf_eeprom.o
obj-y  += inf_mac.o
obj-y  += inf_gpio_expander.o
obj-y  += mmc.o
obj-y  += inf_board.o

obj-$(CONFIG_EA_IMX_PTP)	+= inf_ptp.o

